CREATE DATABASE Delphine
WITH
    OWNER = admin ENCODING = 'UTF8';

CREATE ROLE delphine_scrapers LOGIN PASSWORD 'securepassword'
CONNECTION
LIMIT 99;

GRANT CONNECT ON DATABASE delphine TO delphine_scrapers;

CREATE SCHEMA IF NOT EXISTS kb;

GRANT USAGE ON SCHEMA kb TO delphine_scrapers;

GRANT
SELECT,
INSERT,
UPDATE,
DELETE ON ALL TABLES IN SCHEMA kb to delphine_scrapers;